services/api/src/utils/logger.ts
This ensures the API's logging is pretty-printed during development.
=> Re-enable pretty print for development

apps/web/src/components/releases/release-filter-type.tsx, apps/web/src/components/toggle/toggle.module.css
The disabled state for the switch component is indistinguishable from the enabled state. This is better at least for now.
-- I'd also be happy to take a swing at disabled state styles if people don't like show/hide in this context.
=> Hide auction filters when auctions are filtered out

.github/workflows/deploy.yml
Passing Terraform input variables in via environment variables requires a specific convention, namely that a variable called `my_variable` would be passed in via `TF_VAR_my_variable=... terraform apply`.
This convention was followed with the github secrets themselves, meaning the [deploy file](https://github.com/deptagency/algomart/blob/6f7f3f1cac2588c9d44c01447c01f397c53b3cd1/.github/workflows/deploy.yml#L126) had lines like...
```
TF_VAR_api_creator_passphrase: ${{ secrets.TF_VAR_api_creator_passphrase }}
```
Since all of the environment variables had to be manually mapped to pass them through to Terraform, following that convention was unnecessary. Furthermore, it introduces some confusion because creating a new Github Secret named `TF_VAR_api_creator_passphrase` _looks like_ it saves …
=> Remove TF_VAR_ prefix from github secrets

.github/workflows/deploy.yml
This PR changes the deploy workflow to use the `development` environment (which is configured with secrets). An environment isn't strictly necessary, but it makes it easier to expand the deployed environment setup if desired.
=> Target development environment in deploy workflow

CONTRIBUTING.md, README.md, apps/web/src/components/collectibles/collectible-browser.module.css, apps/web/src/components/collectibles/collectible-browser.tsx
Set background of flip cards to black so varying image sizes don't accidentally show-through to the back side of the video (per feedback from Ian).
Also automatically play/pause on flip so we don't waste cpu and so we can support audio in the future if need-be.
https://user-images.githubusercontent.com/1179515/140423529-e742efe4-c23e-40a1-b8fb-a21e1ce6dc07.mp4
(opacity set to 50% so you can see the automatic play/pause on flip)
=> Video fit and finish

apps/cms/scripts/bootstrap.mjs
Fixes situation where admin user wouldn't get created if LOG_LEVEL wasn't set due to an additional log statement.
=> Set log level always on directus user count

docs/deploy/04-github-secrets/README.md, terraform/sample.terraform.tfvars
The documentation wasn't clear when `https://` was and was not necessary for various secrets and Terraform variables, which is really problematic because the node libraries that parse urls require 'https://' and the domain mappings must not. Additionally, there were several TODO items in one of the tables. This PR tries to clear all of tha tup.
=> Documentation fixes & additions

apps/web/src/clients/api-client.ts, apps/web/src/components/modals/claim-nft-modal.tsx, services/api/src/modules/packs/packs.service.ts
Closes #67 
Redeeming a pack with unminted assets will fail due to user invariant. This PR:
- Removes the invariant
- Updates the status text
- Increases `defaultTimeout` to 30s to minimize cancelled requests
=> [#67] Fix redeeming unminted assets

apps/web/locales/en-US/common.json, apps/web/src/components/pack-grid/pack-grid.module.css, apps/web/src/components/pack-grid/pack-grid.tsx, apps/web/src/components/pack-grid/pack-item.module.css, apps/web/src/components/pack-grid/pack-item.tsx, apps/web/src/components/pack-grid/pack-placeholder.module.css, apps/web/src/components/pack-grid/pack-placeholder.tsx, package-lock.json, services/api/package.json
- Adjust layouts of revealed cards in pack so that if there's one or two, they're prominently centered. If there's more, it defaults to the grid layout. Also adjusts some of the styles in the cards so the sizes aren't stretched undesirably.
- Adds `hideContent` prop to pack grid. When true, it only shows the question mark, and not the pack metadata, which is arguably only relevant in packs that have many cards. Right now, this shows content if there are 3 or more.
- Also added the "View In My Collection" button from the designs.
- Ran into an issue in DRL implementation (which uses some more up-to-date packages) where the API's knex migrations will fail since they're triggered using the node binary. This PR adds TS Node to ensure it compiles.
=> [MISC] Pack Opening improvements & TS Node Fix

README.md
Ran into this issue on a separate Algomart project where an issue installing dependencies for `node-canvas` came up. https://github.com/Automattic/node-canvas/issues/1733#issuecomment-762659473
If these weren't manually installed, running `npm install` would generate a bunch of `node-gyp` errors.
=> Update documentation with note about system dependencies for M1 Macs

apps/cms/.env.example, apps/web/.env.example, apps/web/src/components/bank-account-form/sections/bank-account-success.tsx, apps/web/src/contexts/payment-context.tsx, packages/schemas/src/payments.ts, services/api/.env.example, services/api/src/lib/circle-adapter.ts, services/api/src/modules/payments/payments.service.ts, services/api/src/tasks/index.ts, services/api/src/tasks/update-payment-bank-statuses.task.ts, services/api/src/utils/format-currency.ts
- Scheduled task for updating wire payment method statuses
- Adding to the payment statuses task to support checking for wire transfers
Closes #76
- In the web's env file, set `NEXT_PUBLIC_WIRE_PAYMENT_ENABLED` to `true`
- Create a purchase or auction type pack in the CMS with a price higher than 3000 (assuming USD is the currency used for web/api)
- Purchase pack and save wire details (or keep page open to reference)
- Mock wire transfer using [this endpoint](https://developers.circle.com/reference#payments-payments-mock-create); the `trackingRef` will match the `trackingRef` in the response (or Tracking Reference in the UI).
We are looking at payments within the past 24 hours, since we have to get all wire transfer payments and check for a matching source ID. Since an amount is not …
=> [#76] Task for checking wire transfers

apps/cms/extensions/displays/pack-price/package.json, apps/cms/extensions/interfaces/price-conversion/package.json, apps/cms/package.json, package-lock.json, services/api/src/lib/directus-adapter.ts, services/api/src/modules/collectibles/collectibles.service.ts, services/api/src/modules/packs/packs.service.ts
Due to issues with the latest version of Directus, downgrade until the issues have been resolved.
Also follows the suggested filter format and use `_eq` for basic comparisons.
=> Downgrade Directus to 9.0.1

README.md
Out of the box, the CMS is located at `http://localhost:8085` not `http://localhost:3001`. Just a small change to fix this.
=> Update Readme to point to correct url for CMS

apps/cms/snapshot.yml
CMS deployment is broken due to the snapshot file referring to a `cms` postgres schema that is not being used. Switching it to public _should_ take care of this.
Note that locally you'll want to switch to a matching setup:
```env
DB_CLIENT="pg"
DB_CONNECTION_STRING="postgres://user:pass@host:5432/name"
DB_SEARCH_PATH="public"
```
=> fix cms snapshot

apps/web/tailwind.config.js
Very minor fix and only affects the VS Code Tailwind extension. Basically, it cannot parse `node:` imports.
=> tailwind.config.js requires non-node protocol

.github/workflows/continuous-deployment.yml
This will fix warnings like:
> google-github-actions/setup-gcloud is pinned at HEAD. We strongly advise against pinning to "@master" as it may be unstable. Please update your GitHub Action YAML from: uses: 'google-github-actions/setup-gcloud@master' to: uses: 'google-github-actions/setup-gcloud@v0' Alternatively, you can pin to any git tag or git SHA in the repository.
=> Use specific version for github action

README.md, apps/cms/README.md, tools/executors/directus/impl.js, tools/executors/directus/impl.ts
Fix of various typos and missing clarity of READMEs.
Added an additional step to CMS setup regarding creating a DB schema that matches the `DB_SEARCH_PATH` environment variable. The env example has `cms` as a value there, so if you keep that value without creating a schema, `nx bootstrap cms` will fail.
BUT it will tell you it succeeded - so I additionally modified the executor to throw an error if there's an error instead of always returning success.
May also modify bottom portion of the CMS Readme before merge, see: https://rocketinsights.slack.com/archives/C01RTKC55R6/p1643668237913089
=> Readme typos, clarity. Better directus executor failing

apps/api/.env.example, apps/api/src/configuration/index.ts, apps/api/src/locales/en-US/emails.json, apps/api/src/modules/notifications/notifications.service.ts, apps/api/src/modules/packs/packs.service.ts, apps/api/src/modules/payments/payments.service.ts, apps/cms/snapshot.yml, apps/web/src/components/button.tsx, apps/web/src/components/ellipsis-loader/ellipsis-loader.module.css, apps/web/src/components/ellipsis-loader/index.tsx, apps/web/src/pages/admin/transactions/[transactionId].tsx, apps/web/src/pages/admin/transactions/transaction.module.css, apps/web/src/styles/globals.css, libs/schemas/src/notifications.ts
This adds user notifications for the following events:
- payment complete
- payment failed
- pack revoked
and customer service notifications for:
- awaiting wire payment
- wire payment success
- wire payment failure
Other changes
- add a `busy` prop to `Button` 
- attempt to fix the weird loss of theme styles issue we see from time to time with tailwind by moving the global css variables out of `@layer base`
- make NFT Template preview image read-only after publish
=> Notifications

README.md, apps/api/README.md, apps/api/package.json, apps/api/scripts/drop.mjs, apps/api/scripts/utils.mjs, apps/cms/README.md, apps/cms/scripts/drop.mjs
Scripts to drop and recreate the databases in API and CMS.
Can be used to re-initialize the whole project like this:
```
nx drop api &&\
nx run api:migrate:latest &&\
nx drop cms &&\
nx bootstrap cms &&\
nx import cms
```
=> Add drop scripts

apps/cms/snapshot.yml
**Changes:**
- Adds filters when:
- selecting Pack Template for NFT Template
- selecting NFT Templates for Pack Template 
- Adds some more notes/comments for various fields.
- Adds required flags for many fields (that were not nullable).
- Re-order some fields in the Directus UI.
- Adds conditions to enforce required Price and Auction Until values for Pack Template.
- Show translation Name/Title where available (may not always work).
- Make Pack Template a readonly field on NFT Template
- Disallow setting both Set and Collection on an NFT Template
- Add a few more field notes
- Allow edits to Sets and Collections after being published
Apologies for the `public` changes, must be a difference in Directus 9.4.x to 9.5.x in how they serialize the schemas.
=> Update CMS schema snapshot

apps/api/src/modules/accounts/accounts.service.ts, apps/api/src/utils/errors.ts
This an alternative fix for the error Ian discovered in #296 
1. Backup two commits to **reproduce**  -- The `POST /accounts` endpoint is set up to write a new UserAccount to the DB then make an HTTP call with got that responds 401.
1.  The POST Accounts should respond with an error
2.  A DB record should be written to the UserAccounts table, **this is the buggy behavior**
2. Move forward one commit to **fix**
1.  The POST Accounts should respond with an error. **Regression test:** this error should be functionally equivalent to the error response in step 1.i  (e.g. it should not be a generic 500, it should forward the status code returned by got)
2.  A DB record should be **not** be written to the UserAccounts table, **this is the correct behavior**
Screen cap: …
=> Rollback DB transaction when an error is thrown

terraform/cloud_run_api.tf, terraform/cloud_run_cms.tf, terraform/cloud_run_web.tf
Just noticed that the Web instance at demo.algomart.dev scales from 0 to 100 instances. To make this demo site more conservative of its resources I'm hard-coding the min/max for each to 1/1.
=> Force single instance for Web, API, and CMS

.github/workflows/continuous-deployment.yml, terraform/cloud_run_api.tf, terraform/nat_gateway.tf, terraform/variables.tf
Ensures the API uses a static outbound API in GCP.
=> Configure static outbound IP for the API

apps/web/languages/en-US/common.json, apps/web/src/components/app-footer/sections/app-footer-currency.tsx, apps/web/src/components/app-footer/sections/app-footer-language.tsx, apps/web/src/components/auth-inputs/auth-inputs.tsx, apps/web/src/components/profile/my-profile-currency.tsx, apps/web/src/components/profile/my-profile-image.tsx, apps/web/src/components/profile/my-profile-language.module.css, apps/web/src/components/profile/my-profile-language.tsx, apps/web/src/components/profile/my-profile-nav.tsx, apps/web/src/components/profile/my-profile-theme.tsx, apps/web/src/components/select-input/select-input.tsx, apps/web/src/components/select-input/select.module.css, apps/web/src/components/select/select.module.css, apps/web/src/components/select/select.tsx, apps/web/src/contexts/theme-context.tsx, apps/web/src/pages/signup.tsx, apps/web/src/templates/login-email-template.tsx, apps/web/src/templates/my-profile-setup-template.tsx, apps/web/src/templates/my-profile-template.tsx, apps/web/src/templates/reset-password-template.tsx, apps/web/src/templates/signup-template.tsx
- Enable themes in production
- FIX: app doesn't remember your selected theme
- add a listener to OS theme changes when using OS theme so it updates without refresh.
- Added Theme selection dropdown to profile page
- FIX: broken select styles and markup related to icons and z-indexing.
- FIX: make it possible to log out on mobile (button is hidden)
- New `Select` input with a more standard API (`value`, `onChange`, `defaultValue`)
- will phase out other Select in a future PR
- Reduce prop-drilling `t` into auth-inputs
https://user-images.githubusercontent.com/1179515/161835522-120d8ff4-d820-4a0a-b287-8d051447b5cc.mp4
=> Themes & Bug fixes

apps/web/src/pages/_document.tsx
https://nextjs.org/docs/basic-features/font-optimization
> Automatic Webfont Optimization currently supports Google Fonts and Typekit with support for other font providers coming soon. We're also planning to add control over [loading strategies](https://github.com/vercel/next.js/issues/21555) and font-display values.
=> Load font from Google Fonts to enable font optimization

apps/web/src/components/app-footer/sections/app-footer-currency.tsx, apps/web/src/components/app-footer/sections/app-footer-language.tsx, apps/web/src/components/app-link/app-link.tsx, apps/web/src/components/profile/my-profile-currency.tsx, apps/web/src/components/profile/my-profile-language.tsx, apps/web/src/contexts/auth-context.tsx, apps/web/src/pages/signup.tsx, apps/web/src/services/auth-service.ts, apps/web/src/utils/cookies-web.ts
- Fix: app-link was being passed locale, not language (they are distinct)
- Fix: Signup flow currency/language choices were not being reflected in the footer after successful signup
- Fix: Anonymous footer currency/language choices were not updating user profile once logged in
- Refactor: Auth service updateCurrency and updateLanguage updates cookies, reducing cookie setting duplication
- @afraser annoyingly the app-footer-language and app-footer-currency components still need to set them manually, if you're logged out
- Refactor: Made specific setCurrency and setLanguage cookie utils to minimize additional code duplication
=> Several i18n fixes

apps/web/languages/en-US/common.json, apps/web/src/components/featured-pack/featured-pack.tsx, apps/web/src/components/media-gallery/media-gallery.tsx, apps/web/src/pages/releases/[packSlug].tsx, apps/web/src/templates/release-template.tsx
`git cherry-pick`'d a bucket-list of items. Need to verify some of the image stuff in the morning, seems some commit competition that's direction rather than syntax; so I'll check in on that & ping here when GTG.
New PR from `origin` instead of `lefnire` (https://github.com/deptagency/algomart/pull/371)
=> Wire amount formatting; winning bidder fix; media gallery fixes

README.md, apps/api/.env.example, apps/api/README.md, apps/cms/.env.example, apps/cms/README.md, apps/scribe/.env.example, apps/scribe/README.md, apps/web/.env.example
Motivation: This PR updates some notes in the README files and adds some examples to the `.env` sample files to add more clarity around the setup process
=> Added some notes to `README`’s and `.env.sample`’s
