deptagency/algomart

apps/web/src/components/profile/my-profile-nav.tsx, apps/web/src/pages/my/collectibles.tsx, apps/web/src/pages/my/collections/index.tsx, apps/web/src/pages/my/showcase.tsx
Fix the redirect to `/brands` to be to `/releases`
=> Fix old references to /brands

apps/web/locales/en-US/common.json, apps/web/src/components/passphrase-input/passphrase-input.tsx, apps/web/src/components/redeem-code/redeem-code.tsx
=> Allow passphrase to be  non-numeric

services/api/src/modules/packs/packs.service.ts
=> [#47] Error when viewing 1 pack per user when having other purchases

apps/web/src/components/releases/release-filters-mobile.module.css, apps/web/src/components/releases/release-filters-mobile.tsx, apps/web/src/templates/releases-template.module.css, apps/web/src/templates/releases-template.tsx
Tablet + (unchanged)
<hr />
Mobile closed
<hr />
Mobile opened
<hr />
https://user-images.githubusercontent.com/781839/142349683-d3b97bee-0629-437a-b8f0-a8027835a0fe.mov
=> Small screen releases filter dialog

packages/schemas/src/accounts.ts, services/api/src/lib/algorand-adapter.ts, services/api/src/migrations/20211116210509_make_creation_transaction_nullable.ts, services/api/src/models/algorand-account.model.ts, services/api/src/modules/accounts/accounts.service.ts, services/api/src/modules/accounts/tests/accounts.routes.test.ts, services/api/src/modules/packs/packs.service.ts, services/api/src/shared/dependency-resolver.ts
=> Delay initial balance

apps/cms/extensions/displays/pack-price/package.json, apps/cms/extensions/interfaces/price-conversion/package.json, apps/cms/package.json, package-lock.json
This version seems to work well on my end and I don't see the issues from before.
=> Upgrade Directus to v9.2.0

services/api/src/lib/algorand-adapter.ts, services/api/src/lib/circle-adapter.ts, services/api/src/lib/directus-adapter.ts, services/api/src/lib/nft-storage-adapter.ts, services/api/src/modules/collectibles/collectibles.service.ts, services/api/test/build-test-app.ts
For the major services, ensure each connection is tested upfront to ensure things are configured correctly. Also ensure the CMS file permssions have public read access.
=> Test connections for third-party integrations

package-lock.json
Using node version `16.13.2`, npm version `8.1.2` when installing includes these changes to the `package-lock.json`.
=> Batch upgrade minor and patch dependencies Pt 2

apps/api/src/migrations/20220121185823_add_collectible_auctions.ts
Adds CollectibleAuction and CollectibleAuctionBid tables, part of #216
=> Add migration for marketplace

apps/api/src/models/collectible-auction-bid.model.ts, apps/api/src/models/collectible-auction.model.ts, libs/schemas/src/collectibles.ts
Add corresponding schema and models for the migrations for #216
=> Add marketplace schema and models

apps/api/src/modules/payments/payments.service.ts, apps/web/src/pages/admin/transactions/[transactionId].tsx, apps/web/src/pages/admin/transactions/index.tsx, libs/schemas/src/packs.ts, libs/schemas/src/payments.ts
- Type fix to prevent "allowBidExpiration is required" error when calling the getting payment by ID endpoint
=> Type error bug fix

apps/cms/README.md
I'm thinking of renaming and reusing Sets as "Groups" for the About You mart. In the process, I took at look at how sets currently work, and noticed the below inconsistencies in the docs.
=> Correct Sets documentation

apps/api/src/index.ts, apps/api/src/utils/logger.ts
=> Log formatted timestamps

apps/cms/README.md, apps/cms/scripts/seed.mjs
- Updating the README for the CMS to have updated details about the Application and Countries collections. 
- Updating seed script to add application and application countries records.
=> Updates to documentation and seed script

.github/workflows/continuous-deployment.yml
kick off CD job to recreate API & CMS
=> Add manual trigger for work flow

apps/cms/snapshot.yml, apps/web/src/components/head-tag/head-tag.tsx, apps/web/src/pages/_document.tsx
🤞 hoping this re-generated snapshot.yml file will fix the deployment issues
Also included a fix for a Next.js warning about including `<link rel="stylesheet" />` tags in `next/head`: https://nextjs.org/docs/messages/no-stylesheets-in-head-component
=> Attempted fix for snapshot

apps/cms/snapshot.yml
Removing fields that were causing issues, this should fix the DB import stage
=> Another fix for the CMS snapshot

apps/api/src/modules/packs/packs.service.ts, apps/cms/snapshot.yml
- Fixes for CMS snapshot
- Fix for "untransferred" packs
=> More fixes

apps/api/src/contracts/auction_approval.teal, contracts/poetry.lock, contracts/pyproject.toml, contracts/src/contracts/auction.py, contracts/src/contracts/utils.py, contracts/tests/test_auction.py
Auction contract is now updated to support a royalty fee paid to the creator account. Also included are changes to _only_ pay the bid amount to the seller and return everything else to the creator (including the royalty fee). One notable  difference is that when closing the auction, both the seller and creator addresses will need to be referenced in the app no-op transaction.
The current version of the contract does still _not_ allow closing it while the auction is active. This might be changed based on our needs.
When reviewing this PR, feel free to skip the `auction_aproval.teal` file as it's generated by the PyTEAL contract.
See previous PR notes below.
---
Some early draft notes:
```
actors:
banker (funding wallet owned by algomart)
creator (temporary account that creates the smart …
```
=> Update smart contract to support royalty fee

.gitignore, README.md, docker-compose.deploy.yml, docker-compose.yml, docker/local/api/Dockerfile, docker/local/api/run.sh
A couple of improvements to make docker-compose` work for local development, as well as some README additions.
=> Docker additions

apps/api/src/lib/algorand-adapter.ts, apps/api/src/modules/collectibles/collectibles.service.ts
Instead, the funding account will create all assets (NFTs) from now on.
- [Old collectible with random creator account](https://testnet.algoexplorer.io/asset/78302265)
- [New collectible with fixed creator account](https://testnet.algoexplorer.io/asset/79827496) ([vanity address](https://github.com/smonn/algorand-vanity) FTW)
Closes #372
=> Remove creator account from asset creation

.dockerignore, .pino-prettyrc, apps/scribe/project.json, apps/scribe/src/configuration/configure-resolver.ts, docker-compose.deploy.yml, docker-compose.yml, docker/deploy/api/run.sh, docker/deploy/scribe/Dockerfile, docker/deploy/scribe/run.sh, docker/local/api/Dockerfile, docker/local/api/run.sh, docker/local/cms/Dockerfile, docker/local/cms/run.sh, docker/local/scribe/Dockerfile, docker/local/scribe/run.sh, docker/local/web/Dockerfile, docker/local/web/run.sh, package-lock.json, package.json
Will need some tweaks, docker-compose is not fully working. May need Directus to bump the Sharp version.
=> Update docker setup for scribe

package.json
Note: this only affects development logs.
=> Ignore/hide severity from JSON via pino-pretty

apps/web/src/hooks/use-pack-filter.tsx, apps/web/src/pages/releases/index.tsx, package-lock.json, package.json
Filters are now conjoined with the URL for deep linking (and also helps with load testing).
=> Apply URL Search params to releases page

apps/cms/package.json, apps/cms/scripts/directus.mjs, apps/cms/scripts/seed-countries.mjs, apps/cms/scripts/seed-data/factories.mjs, apps/cms/scripts/seed-dev.mjs, apps/cms/scripts/seed-languages.mjs, apps/cms/scripts/seed-prod.mjs, apps/cms/scripts/webhooks.mjs
- refactoring seeds into reusable functions
- switching to directus sdk
- splitting dev and prod for easy theoretical prod setup
=> seed script refactors

apps/web/src/pages/_app.tsx, apps/web/src/pages/index.tsx
was missing redirect to lang on load, and document direction change if rtl language selected
=> lang redirect, ltr->rtl change

libs/shared/adapters/src/lib/cms-cache-adapter.ts
- moving querybuild select to common function
- replace custom paging with built in paging
- fix total count
=> refactor paging query

apps/api/src/modules/accounts/accounts.routes.ts, apps/api/src/modules/accounts/index.ts, libs/shared/services/src/lib/accounts.service.ts
- Removing unused endpoints in accounts routes (/:username and /:email lookups)
=> Removing unused endpoints
